s = set()

n = input("Enter the number :\n")
s.add(n)
n = input("Enter the number :\n")
s.add(n)
n = input("Enter the number :\n")
s.add(n)
n = input("Enter the number :\n")
s.add(n)
n = input("Enter the number :\n")
s.add(n)
n = input("Enter the number :\n")
s.add(n)
n = input("Enter the number :\n")
s.add(n)
n = input("Enter the number :\n")
s.add(n)

print(s)
